// Publish speeding violation
POST http://127.0.0.1:6001/collectfine
Content-Type: application/json

{ "license_number": "RT-318-K", "road_id": "A12", "excess_speed": 15, "timestamp": "2020-09-20T08:33:41" }